# Generated by Django 2.2 on 2021-06-09 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_yum123', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='zip_code',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
