# Generated by Django 2.2 on 2021-06-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_yum123', '0002_auto_20210608_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restau_api_obj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('ratings', models.CharField(max_length=45)),
            ],
        ),
    ]
