# Generated by Django 2.2 on 2021-06-14 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_yum123', '0005_auto_20210613_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
